version: '3'
services:
  fuse:
    image: pc-bus-opentext-card-image
    ports:
        - "8181:8181"
        - "8101:8101"
        - "61616:61616"
        - "5005:5005"
  mockserver:
    image: jamesdbloom/mockserver
    ports:
        - "1080:1080"
        - "1090:1090"
  cucumber:
    image: cucumber
